import { db } from '../db.js';
export const summary=async(_req,res)=>{ const [[{totalUsers}]]=await db.query('SELECT COUNT(*) totalUsers FROM users');
 const [[{totalCompanies}]]=await db.query('SELECT COUNT(*) totalCompanies FROM companies');
 const [recent]=await db.query('SELECT c.id,c.fantasy_name,c.updated_at,u.name AS updated_by_name FROM companies c LEFT JOIN users u ON u.id=c.updated_by ORDER BY c.updated_at DESC LIMIT 10');
 res.json({totalUsers,totalCompanies,recent}); };
export const charts=async(_req,res)=>{ const [a]=await db.query('SELECT COALESCE(sector,"—") label, COUNT(*) value FROM companies GROUP BY 1 ORDER BY 2 DESC');
 const [b]=await db.query('SELECT role label, COUNT(*) value FROM users GROUP BY 1');
 const [c]=await db.query("SELECT DATE_FORMAT(created_at,'%Y-%m') label, COUNT(*) value FROM companies WHERE created_at >= DATE_SUB(CURDATE(), INTERVAL 11 MONTH) GROUP BY 1 ORDER BY 1 ASC");
 res.json({companiesBySector:a, usersByRole:b, companiesByMonth:c}); };
export const commissions=async(req,res)=>{ const p=req.query.period; const first=p?`${p}-01`:null;
 const [rows]=await db.query('SELECT u.id user_id, u.name consultant, SUM(a.monthly_fee*(a.commission_rate/100)) commission_value, COUNT(DISTINCT a.company_id) companies FROM associates a JOIN users u ON u.id=a.consultant_id WHERE (? IS NULL OR (a.start_date <= LAST_DAY(?) AND (a.end_date IS NULL OR a.end_date >= ?))) GROUP BY 1,2 ORDER BY commission_value DESC',[first,first,first]);
 res.json({items:rows}); };
